name: Hourly DAT data update

on:
  schedule:
    - cron: "5 * * * *"   # run at minute 5 each hour (UTC)
  workflow_dispatch:       # allow manual run from the Actions tab

permissions:
  contents: write

concurrency:
  group: hourly-dat
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write .env from secret
        run: |
          echo "ARTEMIS_API_KEY=${{ secrets.ARTEMIS_API_KEY }}" > .env

      - name: Run data update script
        run: |
          python art_dat.py

      - name: Build ID for cache-busting
        id: build
        run: |
          echo "BUILD_ID=$(date -u +%Y%m%d%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Bump CSS/JS versions in index.html
        run: |
          # Replace existing ?v=... for styles.css and app.js with current BUILD_ID
          sed -i 's#styles.css?v=[^"]*#styles.css?v='${{ steps.build.outputs.BUILD_ID }}'#' docs/index.html || true
          sed -i 's#app.js?v=[^"]*#app.js?v='${{ steps.build.outputs.BUILD_ID }}'#' docs/index.html || true

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/dat_data.csv docs/index.html .env || true
          git reset -- .env || true   # never commit secrets
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update data & cache-bust: ${{ steps.build.outputs.BUILD_ID }}"
            git push
          else
            echo "No changes to commit."
          fi